# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/BabyBus',
                'doc_host': 'https://songwupei.github.io',
                'git_url': 'https://github.com/songwupei/BabyBus',
                'lib_path': 'BabyBus'},
  'syms': {'BabyBus.core': {'BabyBus.core.foo': ('core.html#foo', 'BabyBus/core.py')}}}
